<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE table
[
  <!ELEMENT table	(tuple)*>
  <!ATTLIST table
            name	CDATA #REQUIRED
  >

  <!ELEMENT tuple	(table|tuple|atom)*>
  <!ATTLIST tuple
            name	CDATA #IMPLIED
  >

  <!ELEMENT atom	(#PCDATA)*>
  <!ATTLIST atom
            name	CDATA #REQUIRED
            type	CDATA "text"
            size	CDATA "short"
  >
]
>
<?schema
  table           ecatalogue
    integer         irn
    text short      AdmPublishWebNoPassword
    text short      TitAccessionNo
    text short      TitPreviousAccessionNo
    text short      TitObjectStatus
    date            TitAccessionDate
    text long       TitMainTitle
    text long       TitSeriesTitle
    text long       TitCollectionTitle
    table           AltTitles
      text long       TitAlternateTitles
    end
    text long       TitTitleNotes
    text short      TitObjectType
    table           ObjectTypes
      text short      PhyMediaCategory
    end
    text short      CreDateCreated
    date            CreEarliestDate
    date            CreLatestDate
    text short      CreCreationPeriod
    text long       CreCreationDynasty
    table           Creator1
      text short      CreRole
      text long       CreCreatorAfterFollower
      integer         irn
      text long       SummaryData
    end
    table           Creator2
      text long       CreCreatorAttribution
      text long       CreCreationCultureOrPeople
      text long       CreCreationNationality2
    end
    table           CreLocation
      text short      CreCountry
      text short      CreState
      text short      CreDistrict
      text short      CreCity
    end
    table           MarkType
      text short      CreMarkType
    end
    text long       CrePrimaryInscriptions
    text long       CreCreationNotes
    date            EdiPublisherDate
    table           Medium
      text long       PhyMedium
    end
    table           Support
      text short      PhySupport
    end
    text long       PhyMediumAndSupport
    text short      PhyStyle
    text short      PhyTechnique
    text short      EdiImpression
    text long       PhyDescription
    table           Color
      text short      PhyColor
    end
    text long       PhyConvertedDims
    table           Dimensions
      text short      PhyType
      float           PhyHeight
      float           PhyWidth
      float           PhyDepth
      float           PhyDiameter
      text short      PhyUnitLength
      float           PhyWeight
      text short      PhyUnitWeight
      text short      PhyDimensionNotes
    end
    text long       SumCreditLine
    table           Rights
      text long       RigAcknowledgement
    end
    text long       CreProvenance
    text short      PhyCollectionArea
    text short      LocMovementType
    tuple           LocCurrentLocationRef
      text short      LocLevel1
      text short      LocLevel2
      text short      LocLevel3
    end
    tuple           AssParentObjectRef
      integer         irn
    end
    text short      AssIsParent
    table           Children
      integer         irn
      text long       TitMainTitle
      table           Grandchildren
        integer         irn
        text long       TitMainTitle
      end
    end
    table           Related
      text short      AssRelationship
      integer         irn
    end
    text short      AdmPublishWebNoPassword
    table           Homepage
      text short      RefBibliographicNotes
      integer         irn
      text long       EleTitle
      text short      EleIdentifier
    end
  end
?>
<!-- Data -->
<table name="ecatalogue">

  <!-- Row 1 -->
  <tuple>
    <atom name="irn">1032</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="TitAccessionNo">60.63</atom>
    <atom name="TitPreviousAccessionNo">TR5488/1</atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionDate">1960-10-10</atom>
    <atom name="TitMainTitle">long-neck vase with cup mouth</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <atom name="TitTitleNotes"></atom>
    <atom name="TitObjectType">Containers</atom>
    <table name="ObjectTypes">
      <tuple>
        <atom name="PhyMediaCategory">stoneware</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated">100-220</atom>
    <atom name="CreEarliestDate">100</atom>
    <atom name="CreLatestDate">220</atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty">Eastern Han dynasty</atom>
    <table name="CreLocation">
      <tuple>
        <atom name="CreCountry">China</atom>
      </tuple>
    </table>
    <atom name="CrePrimaryInscriptions"></atom>
    <atom name="CreCreationNotes"></atom>
    <atom name="EdiPublisherDate"></atom>
    <atom name="PhyMediumAndSupport">stoneware, green glaze</atom>
    <atom name="PhyStyle"></atom>
    <atom name="PhyTechnique"></atom>
    <atom name="EdiImpression"></atom>
    <atom name="PhyDescription"></atom>
    <atom name="PhyConvertedDims">17-1/4 in.</atom>
    <table name="Dimensions">
      <tuple>
        <atom name="PhyType">Dimensions</atom>
        <atom name="PhyHeight">17.2500</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 43.8</atom>
      </tuple>
    </table>
    <atom name="SumCreditLine">Gift of Mr. and Mrs. Eli Lilly</atom>
    <table name="Rights">
      <tuple>
        <atom name="RigAcknowledgement">Public Domain</atom>
      </tuple>
    </table>
    <atom name="CreProvenance">[Jan W. A. Kleijkamp]; Eli Lilly (May 1950 list noting Nov. 15, 1950 $950.); IMA (60.63)</atom>
    <atom name="PhyCollectionArea">905.1-Asian Art (Chinese and other Asian)</atom>
    <atom name="LocMovementType">Inventory 2014-2015</atom>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">IMA</atom>
      <atom name="LocLevel2">storage</atom>
      <atom name="LocLevel3">Ac1</atom>
    </tuple>
    <tuple name="AssParentObjectRef">
        <atom name="irn"></atom>
    </tuple>
    <atom name="AssIsParent">No</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <table name="Homepage">
      <tuple>
        <atom name="RefBibliographicNotes">23059</atom>
        <atom name="irn">3274</atom>
        <atom name="EleTitle">Dagwood ID for 60.63</atom>
        <atom name="EleIdentifier">23059</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 2 -->
  <tuple>
    <atom name="irn">1065</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="TitAccessionNo">14.55</atom>
    <atom name="TitPreviousAccessionNo">No TR Number</atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionDate">1914-02-19</atom>
    <atom name="TitMainTitle">The Bachelor Boudoir (Corner of the Studio)</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <atom name="TitTitleNotes"></atom>
    <atom name="TitObjectType">Visual Works: Paintings</atom>
    <table name="ObjectTypes">
      <tuple>
        <atom name="PhyMediaCategory">paintings</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">oil paintings</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated">about 1883</atom>
    <atom name="CreEarliestDate">1882</atom>
    <atom name="CreLatestDate">1883</atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="Creator1">
      <tuple>
        <atom name="CreRole">Artist</atom>
        <atom name="irn">733</atom>
        <atom name="SummaryData">Fiscus, Charles J.</atom>
      </tuple>
    </table>
    <table name="CreLocation">
      <tuple>
        <atom name="CreCountry">United States</atom>
      </tuple>
    </table>
    <table name="MarkType">
      <tuple>
        <atom name="CreMarkType">Signature</atom>
      </tuple>
    </table>
    <atom name="CrePrimaryInscriptions">Signed, l.r.: C FISCUS</atom>
    <atom name="CreCreationNotes">Keep "Latest" date as 1883, the year the painting was exhibited at the National Academy of Design.</atom>
    <atom name="EdiPublisherDate"></atom>
    <table name="Medium">
      <tuple>
        <atom name="PhyMedium">oil paint</atom>
      </tuple>
    </table>
    <table name="Support">
      <tuple>
        <atom name="PhySupport">canvas</atom>
      </tuple>
    </table>
    <atom name="PhyMediumAndSupport">oil on canvas</atom>
    <atom name="PhyStyle"></atom>
    <atom name="PhyTechnique">painting</atom>
    <atom name="EdiImpression"></atom>
    <atom name="PhyDescription"></atom>
    <atom name="PhyConvertedDims">27-1/4 x 16-1/4 in. (canvas)
34-3/4 x 24-3/4 x 4 in. (framed)</atom>
    <table name="Dimensions">
      <tuple>
        <atom name="PhyType">Framed Dimensions</atom>
        <atom name="PhyHeight">34.7500</atom>
        <atom name="PhyWidth">24.7500</atom>
        <atom name="PhyDepth">4.0000</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 88.2 x 62.8 x 10.1 (framed)</atom>
      </tuple>
      <tuple>
        <atom name="PhyType">Unframed Dimensions</atom>
        <atom name="PhyHeight">27.2500</atom>
        <atom name="PhyWidth">16.2500</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 69.2 x 41.2 (canvas)</atom>
      </tuple>
    </table>
    <atom name="SumCreditLine">Gift of the Artist's mother, Mrs. E.J. Fiscus</atom>
    <table name="Rights">
      <tuple>
        <atom name="RigAcknowledgement">Public Domain</atom>
      </tuple>
    </table>
    <atom name="CreProvenance"></atom>
    <atom name="PhyCollectionArea">901.2-American Painting and Sculpture 1800-1945</atom>
    <atom name="LocMovementType">Other Location</atom>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">IMA</atom>
      <atom name="LocLevel2">Westerley</atom>
      <atom name="LocLevel3">East Bedroom</atom>
    </tuple>
    <tuple name="AssParentObjectRef">
        <atom name="irn"></atom>
    </tuple>
    <atom name="AssIsParent">No</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <table name="Homepage">
      <tuple>
        <atom name="RefBibliographicNotes">56270</atom>
        <atom name="irn">3307</atom>
        <atom name="EleTitle">Dagwood ID for 14.55</atom>
        <atom name="EleIdentifier">56270</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 3 -->
  <tuple>
    <atom name="irn">1105</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="TitAccessionNo">1989.1569</atom>
    <atom name="TitPreviousAccessionNo">E84.43</atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionDate"></atom>
    <atom name="TitMainTitle">bowl</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <atom name="TitTitleNotes"></atom>
    <atom name="TitObjectType">Containers</atom>
    <table name="ObjectTypes">
      <tuple>
        <atom name="PhyMediaCategory">bowls</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated">late 19th century</atom>
    <atom name="CreEarliestDate">1850</atom>
    <atom name="CreLatestDate">1897</atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="Creator2">
      <tuple>
        <atom name="CreCreationCultureOrPeople">Benin Kingdom</atom>
      </tuple>
      <tuple>
        <atom name="CreCreationCultureOrPeople">Edo people</atom>
      </tuple>
    </table>
    <table name="CreLocation">
      <tuple>
        <atom name="CreCountry">Nigeria</atom>
      </tuple>
    </table>
    <atom name="CrePrimaryInscriptions"></atom>
    <atom name="CreCreationNotes"></atom>
    <atom name="EdiPublisherDate"></atom>
    <table name="Medium">
      <tuple>
        <atom name="PhyMedium">brass</atom>
      </tuple>
      <tuple>
        <atom name="PhyMedium">gold</atom>
      </tuple>
    </table>
    <table name="Support">
      <tuple>
        <atom name="PhySupport">brass</atom>
      </tuple>
      <tuple>
        <atom name="PhySupport">gold</atom>
      </tuple>
    </table>
    <atom name="PhyMediumAndSupport">brass with gold covering</atom>
    <atom name="PhyStyle"></atom>
    <atom name="PhyTechnique"></atom>
    <atom name="EdiImpression"></atom>
    <atom name="PhyDescription"></atom>
    <atom name="PhyConvertedDims">9 in.</atom>
    <table name="Dimensions">
      <tuple>
        <atom name="PhyType">Dimensions</atom>
        <atom name="PhyHeight">9.0000</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 22.9</atom>
      </tuple>
    </table>
    <atom name="SumCreditLine">Gift of Mr. and Mrs. Harrison Eiteljorg</atom>
    <table name="Rights">
      <tuple>
        <atom name="RigAcknowledgement">Public Domain</atom>
      </tuple>
    </table>
    <atom name="CreProvenance">(Christie's London) sold on June 25, 1984 to Harrison Eiteljorg [1903-1997] of Indianapolis; donated to the IMA 1989</atom>
    <atom name="PhyCollectionArea">906.1-African Art</atom>
    <atom name="LocMovementType">Exhibition Location</atom>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">IMA</atom>
      <atom name="LocLevel2">Eiteljorg Suite of African and Oceanic Art</atom>
      <atom name="LocLevel3">W302</atom>
    </tuple>
    <tuple name="AssParentObjectRef">
        <atom name="irn"></atom>
    </tuple>
    <atom name="AssIsParent">No</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <table name="Homepage">
      <tuple>
        <atom name="RefBibliographicNotes">29429</atom>
        <atom name="irn">3347</atom>
        <atom name="EleTitle">Dagwood ID for 1989.1569</atom>
        <atom name="EleIdentifier">29429</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 4 -->
  <tuple>
    <atom name="irn">3457</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="TitAccessionNo">U477</atom>
    <atom name="TitPreviousAccessionNo"></atom>
    <atom name="TitObjectStatus">Unknown</atom>
    <atom name="TitAccessionDate"></atom>
    <atom name="TitMainTitle">basketry bowl</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <atom name="TitTitleNotes"></atom>
    <atom name="TitObjectType">Containers</atom>
    <table name="ObjectTypes">
      <tuple>
        <atom name="PhyMediaCategory">containers</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">baskets</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">bowls</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated">1900-1950</atom>
    <atom name="CreEarliestDate">1900</atom>
    <atom name="CreLatestDate">1950</atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="Creator2">
      <tuple>
        <atom name="CreCreationCultureOrPeople">Pima people</atom>
      </tuple>
    </table>
    <table name="CreLocation">
      <tuple>
        <atom name="CreCountry">United States</atom>
        <atom name="CreState">Arizona</atom>
      </tuple>
    </table>
    <atom name="CrePrimaryInscriptions"></atom>
    <atom name="CreCreationNotes"></atom>
    <atom name="EdiPublisherDate"></atom>
    <table name="Support">
      <tuple>
        <atom name="PhySupport">plant fiber</atom>
      </tuple>
    </table>
    <atom name="PhyMediumAndSupport">plant fiber</atom>
    <atom name="PhyStyle"></atom>
    <atom name="PhyTechnique">weaving</atom>
    <atom name="EdiImpression"></atom>
    <atom name="PhyDescription">a small woven bowl with a simple decorative dark and light pattern</atom>
    <atom name="PhyConvertedDims">1-1/2 x 7-1/8 x 7-1/8 in.</atom>
    <table name="Dimensions">
      <tuple>
        <atom name="PhyType">Dimensions</atom>
        <atom name="PhyHeight">1.5000</atom>
        <atom name="PhyWidth">7.1250</atom>
        <atom name="PhyDepth">7.1250</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 3.8 x 18.1 x 18.1</atom>
      </tuple>
    </table>
    <atom name="SumCreditLine">Museum Accession</atom>
    <atom name="CreProvenance"></atom>
    <atom name="PhyCollectionArea">906.2-Native Arts of the Americas</atom>
    <atom name="LocMovementType">Inventory Beginning 2018 - ten year schedule for upcoming reaccreditation</atom>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">IMA</atom>
      <atom name="LocLevel2">storage</atom>
      <atom name="LocLevel3">Ec43</atom>
    </tuple>
    <tuple name="AssParentObjectRef">
        <atom name="irn"></atom>
    </tuple>
    <atom name="AssIsParent">No</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <table name="Homepage">
      <tuple>
        <atom name="RefBibliographicNotes">22182</atom>
        <atom name="irn">5686</atom>
        <atom name="EleTitle">Dagwood ID for U477</atom>
        <atom name="EleIdentifier">22182</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 5 -->
  <tuple>
    <atom name="irn">3521</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="TitAccessionNo">42.07</atom>
    <atom name="TitPreviousAccessionNo">TR1658/647</atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionDate">1942-02-17</atom>
    <atom name="TitMainTitle">Still Life with Flowerpot</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <table name="AltTitles">
      <tuple>
        <atom name="TitAlternateTitles">Still Life</atom>
      </tuple>
    </table>
    <atom name="TitTitleNotes"></atom>
    <atom name="TitObjectType">Visual Works: Paintings</atom>
    <table name="ObjectTypes">
      <tuple>
        <atom name="PhyMediaCategory">paintings</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">oil paintings</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated">1930</atom>
    <atom name="CreEarliestDate">1930</atom>
    <atom name="CreLatestDate">1930</atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="Creator1">
      <tuple>
        <atom name="CreRole">Artist</atom>
        <atom name="irn">5060</atom>
        <atom name="SummaryData">Beem, Paul Edward</atom>
      </tuple>
    </table>
    <table name="Creator2">
      <tuple>
        <atom name="CreCreationNationality2">  </atom>
      </tuple>
    </table>
    <table name="CreLocation">
      <tuple>
        <atom name="CreCountry">United States</atom>
      </tuple>
    </table>
    <table name="MarkType">
      <tuple>
        <atom name="CreMarkType">Signature</atom>
      </tuple>
      <tuple>
        <atom name="CreMarkType">Date</atom>
      </tuple>
    </table>
    <atom name="CrePrimaryInscriptions">Signed and dated, l.r.: PAUL E BEEM 30</atom>
    <atom name="CreCreationNotes"></atom>
    <atom name="EdiPublisherDate"></atom>
    <table name="Medium">
      <tuple>
        <atom name="PhyMedium">oil paint</atom>
      </tuple>
    </table>
    <table name="Support">
      <tuple>
        <atom name="PhySupport">canvas</atom>
      </tuple>
    </table>
    <atom name="PhyMediumAndSupport">oil on canvas</atom>
    <atom name="PhyStyle"></atom>
    <atom name="PhyTechnique">painting</atom>
    <atom name="EdiImpression"></atom>
    <atom name="PhyDescription"></atom>
    <atom name="PhyConvertedDims">22 x 24 in. (canvas)
29 x 31 x 2-3/4 in. (framed)</atom>
    <table name="Dimensions">
      <tuple>
        <atom name="PhyType">Framed Dimensions</atom>
        <atom name="PhyHeight">29.0000</atom>
        <atom name="PhyWidth">31.0000</atom>
        <atom name="PhyDepth">2.7500</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 73.7 x 78.7 x 7 (framed)</atom>
      </tuple>
      <tuple>
        <atom name="PhyType">Unframed Dimensions</atom>
        <atom name="PhyHeight">22.0000</atom>
        <atom name="PhyWidth">24.0000</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 55.8 x 61 (canvas)</atom>
      </tuple>
    </table>
    <atom name="SumCreditLine">Gift of Hugh McK. Landon</atom>
    <table name="Rights">
      <tuple>
        <atom name="RigAcknowledgement">© Paul Edward Beem</atom>
      </tuple>
    </table>
    <atom name="CreProvenance"></atom>
    <atom name="PhyCollectionArea">901.2-American Painting and Sculpture 1800-1945</atom>
    <atom name="LocMovementType">Inventory Beginning 2018 - ten year schedule for upcoming reaccreditation</atom>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">IMA</atom>
      <atom name="LocLevel2">storage</atom>
      <atom name="LocLevel3">P</atom>
    </tuple>
    <tuple name="AssParentObjectRef">
        <atom name="irn"></atom>
    </tuple>
    <atom name="AssIsParent">No</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <table name="Homepage">
      <tuple>
        <atom name="RefBibliographicNotes">38014</atom>
        <atom name="irn">5750</atom>
        <atom name="EleTitle">Dagwood ID for 42.07</atom>
        <atom name="EleIdentifier">38014</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 6 -->
  <tuple>
    <atom name="irn">6136</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="TitAccessionNo">1983.100</atom>
    <atom name="TitPreviousAccessionNo"></atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionDate"></atom>
    <atom name="TitMainTitle">PRAISES FOR KSITIGARBA SUTRA (DIZANG JINGZAN)</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <atom name="TitTitleNotes"></atom>
    <atom name="TitObjectType">Visual Works: Prints</atom>
    <table name="ObjectTypes">
      <tuple>
        <atom name="PhyMediaCategory">woodcuts</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated">March-April 1574</atom>
    <atom name="CreEarliestDate">1574-03-01</atom>
    <atom name="CreLatestDate">1574-04-30</atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="CreLocation">
      <tuple>
        <atom name="CreCountry">China</atom>
      </tuple>
    </table>
    <atom name="CrePrimaryInscriptions"></atom>
    <atom name="CreCreationNotes"></atom>
    <atom name="EdiPublisherDate"></atom>
    <table name="Medium">
      <tuple>
        <atom name="PhyMedium">ink</atom>
      </tuple>
    </table>
    <table name="Support">
      <tuple>
        <atom name="PhySupport">paper</atom>
      </tuple>
    </table>
    <atom name="PhyMediumAndSupport">ink</atom>
    <atom name="PhyStyle"></atom>
    <atom name="PhyTechnique"></atom>
    <atom name="EdiImpression"></atom>
    <atom name="PhyDescription"></atom>
    <atom name="PhyConvertedDims">10-11/16 x 3-13/16</atom>
    <atom name="SumCreditLine">Gift of Mr. Keith Uhl Clary</atom>
    <table name="Rights">
      <tuple>
        <atom name="RigAcknowledgement">No Known Rights Holder</atom>
      </tuple>
    </table>
    <atom name="CreProvenance"></atom>
    <atom name="PhyCollectionArea">905.1-Asian Art (Chinese and other Asian)</atom>
    <atom name="LocMovementType">Other Location</atom>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">IMA</atom>
      <atom name="LocLevel2">Eli Lilly and Company Foundation Room</atom>
      <atom name="LocLevel3">K301</atom>
    </tuple>
    <tuple name="AssParentObjectRef">
        <atom name="irn"></atom>
    </tuple>
    <atom name="AssIsParent">No</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <table name="Homepage">
      <tuple>
        <atom name="RefBibliographicNotes">50209</atom>
        <atom name="irn">8354</atom>
        <atom name="EleTitle">Dagwood ID for 1983.100</atom>
        <atom name="EleIdentifier">50209</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 7 -->
  <tuple>
    <atom name="irn">6855</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="TitAccessionNo">1996.114</atom>
    <atom name="TitPreviousAccessionNo"></atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionDate">1996-03-21</atom>
    <atom name="TitMainTitle">hunchback figure</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <atom name="TitTitleNotes"></atom>
    <atom name="TitObjectType">Visual Works: Sculpture</atom>
    <atom name="CreDateCreated">200 B.C.E. - 300 CE</atom>
    <atom name="CreEarliestDate">-200</atom>
    <atom name="CreLatestDate">300</atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="Creator2">
      <tuple>
        <atom name="CreCreationCultureOrPeople">Nayarit culture</atom>
      </tuple>
    </table>
    <table name="CreLocation">
      <tuple>
        <atom name="CreCountry">Mexico</atom>
      </tuple>
    </table>
    <atom name="CrePrimaryInscriptions"></atom>
    <atom name="CreCreationNotes"></atom>
    <atom name="EdiPublisherDate"></atom>
    <atom name="PhyMediumAndSupport">ceramic | pigment</atom>
    <atom name="PhyStyle"></atom>
    <atom name="PhyTechnique"></atom>
    <atom name="EdiImpression"></atom>
    <atom name="PhyDescription"></atom>
    <atom name="PhyConvertedDims">4-1/2 x 2-3/4 x 4-1/2 (gd) in. | 11.4 x 7.0 x 11.4 (gd) cm.</atom>
    <table name="Dimensions">
      <tuple>
        <atom name="PhyType">Dimensions</atom>
        <atom name="PhyHeight">4.5000</atom>
        <atom name="PhyWidth">2.7500</atom>
        <atom name="PhyDepth">4.5000</atom>
        <atom name="PhyUnitLength">in.</atom>
        <atom name="PhyDimensionNotes">Metric: 11.42999983 cm height x 6.984999895 cm width x 11.42999983 cm depth</atom>
      </tuple>
    </table>
    <atom name="SumCreditLine">Gift of Bonnie and David Ross</atom>
    <table name="Rights">
      <tuple>
        <atom name="RigAcknowledgement">Public Domain</atom>
      </tuple>
    </table>
    <atom name="CreProvenance"></atom>
    <atom name="PhyCollectionArea">906.2-Native Arts of the Americas</atom>
    <atom name="LocMovementType">Inventory 2014-2015</atom>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">IMA</atom>
      <atom name="LocLevel2">storage</atom>
      <atom name="LocLevel3">Ec45</atom>
    </tuple>
    <tuple name="AssParentObjectRef">
        <atom name="irn"></atom>
    </tuple>
    <atom name="AssIsParent">No</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <table name="Homepage">
      <tuple>
        <atom name="RefBibliographicNotes">3095</atom>
        <atom name="irn">9070</atom>
        <atom name="EleTitle">Dagwood ID for 1996.114</atom>
        <atom name="EleIdentifier">3095</atom>
      </tuple>
    </table>
  </tuple>

  <!-- Row 8 -->
  <tuple>
    <atom name="irn">8407</atom>
    <atom name="AdmPublishWebNoPassword">Yes</atom>
    <atom name="TitAccessionNo">1984.124</atom>
    <atom name="TitPreviousAccessionNo">TR5417</atom>
    <atom name="TitObjectStatus">Accessioned</atom>
    <atom name="TitAccessionDate">1984-09-20</atom>
    <atom name="TitMainTitle">quilt (Diamond in Square)</atom>
    <atom name="TitSeriesTitle"></atom>
    <atom name="TitCollectionTitle"></atom>
    <atom name="TitTitleNotes"></atom>
    <atom name="TitObjectType">Furnishings</atom>
    <table name="ObjectTypes">
      <tuple>
        <atom name="PhyMediaCategory">furnishings</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">textiles</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">bed coverings</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">quilts</atom>
      </tuple>
      <tuple>
        <atom name="PhyMediaCategory">patchwork quilts</atom>
      </tuple>
    </table>
    <atom name="CreDateCreated">about 1900</atom>
    <atom name="CreEarliestDate">1895</atom>
    <atom name="CreLatestDate">1905</atom>
    <atom name="CreCreationPeriod"></atom>
    <atom name="CreCreationDynasty"></atom>
    <table name="Creator1">
      <tuple>
        <atom name="CreRole">Artist</atom>
        <atom name="irn">2741</atom>
        <atom name="SummaryData">Unknown</atom>
      </tuple>
    </table>
    <table name="Creator2">
      <tuple>
        <atom name="CreCreationCultureOrPeople">Amish people</atom>
      </tuple>
    </table>
    <table name="CreLocation">
      <tuple>
        <atom name="CreCountry">United States</atom>
        <atom name="CreState">Pennsylvania</atom>
        <atom name="CreDistrict">Lancaster County</atom>
      </tuple>
    </table>
    <table name="MarkType">
      <tuple>
        <atom name="CreMarkType">Inscriptions</atom>
      </tuple>
    </table>
    <atom name="CrePrimaryInscriptions">Sewn, back side, lower corner: S P</atom>
    <atom name="CreCreationNotes"></atom>
    <atom name="EdiPublisherDate"></atom>
    <table name="Support">
      <tuple>
        <atom name="PhySupport">cotton {fabric}</atom>
      </tuple>
      <tuple>
        <atom name="PhySupport">wool {fabric}</atom>
      </tuple>
    </table>
    <atom name="PhyMediumAndSupport">wool and cotton, pieced and quilted</atom>
    <atom name="PhyStyle"></atom>
    <atom name="PhyTechnique">quilting</atom>
    <atom name="EdiImpression"></atom>
    <atom name="PhyDescription">wool twill weave and cotton plain weave, pieced and quilted 'diamond in a square' theme</atom>
    <atom name="PhyConvertedDims">70 x 72-1/2 in.</atom>
    <table name="Dimensions">
      <tuple>
        <atom name="PhyType">Dimensions</atom>
        <atom name="PhyHeight">70.0000</atom>
        <atom name="PhyWidth">72.5000</atom>
        <atom name="PhyUnitLength">in.</atom>